Fix error exit on CIs

diff --git a/.github/workflows/tests_gpu_cpp.yml b/.github/workflows/tests_gpu_cpp.yml
--- a/.github/workflows/tests_gpu_cpp.yml
+++ b/.github/workflows/tests_gpu_cpp.yml
@@ -148,10 +148,15 @@ jobs:
           cmake --build ./Build
           cd ./Build
           mkdir -p ./tests/results_${{ github.job }}_${{ matrix.pl_backend }}
+          test_status=0
           for file in *runner ; do 
             report_file="./tests/results_${{ github.job }}_${{ matrix.pl_backend }}/report_$file.xml";
-            ./$file --reporter junit --out $report_file && echo "Test $file Success!" || cat $report_file;
+            ./$file --reporter junit --out $report_file && echo "Test $file Success!" || { cat $report_file; test_status=1; }
           done;
+          if [ $test_status -ne 0 ]; then
+            echo "Tests failed. Exiting with error code."
+            exit 1
+          fi
           lcov --directory . -b ../pennylane_lightning/core/src --capture --output-file coverage.info
           lcov --remove coverage.info '/usr/*' --output-file coverage.info
           mv coverage.info coverage-${{ github.job }}-${{ matrix.pl_backend }}.info
diff --git a/.github/workflows/tests_linux_cpp.yml b/.github/workflows/tests_linux_cpp.yml
--- a/.github/workflows/tests_linux_cpp.yml
+++ b/.github/workflows/tests_linux_cpp.yml
@@ -80,17 +80,20 @@ jobs:
               -DLQ_ENABLE_KERNEL_AVX_STREAMING=${{ matrix.enable_kernel_avx_streaming }} \
               -DLQ_ENABLE_KERNEL_OMP=${{ matrix.enable_kernel_omp }}
 
-            echo "Building"
             cmake --build ./Build
 
             cd ./Build
             mkdir -p ./tests/results
-            echo "Running tests"
-             for file in *runner ; do ./$file  --reporter junit --out ./tests/results/report_$file.xml && echo "Test $file Success!" || cat ./tests/results/report_$file.xml; done;
-            echo "Generating coverage report"
+            test_status=0
+            for file in *runner ; do 
+              ./$file  --reporter junit --out ./tests/results/report_$file.xml && echo "Test $file Success!" || { cat ./tests/results/report_$file.xml; test_status=1; }; 
+            done;
+            if [ $test_status -ne 0 ]; then
+              echo "Tests failed. Exiting with error code."
+              exit 1
+            fi
             lcov --directory . -b ../pennylane_lightning/core/src --capture --output-file coverage.info  --ignore-errors mismatch # Catch2 causes mismatch errors that needs to be ignored
             lcov --remove coverage.info '/usr/*' --output-file coverage.info
-            echo "Moving coverage report"
             mv coverage.info coverage-${{ github.job }}-${{ matrix.pl_backend }}-${{ matrix.enable_kernel_avx_streaming }}-${{ matrix.enable_kernel_omp }}.info
 
       - name: Upload test results
@@ -149,7 +152,14 @@ jobs:
             cmake --build ./Build
             cd ./Build
             mkdir -p ./tests/results
-             for file in *runner ; do ./$file  --reporter junit --out ./tests/results/report_$file.xml && echo "Test $file Success!" || cat ./tests/results/report_$file.xml; done;
+            test_status=0
+             for file in *runner ; do 
+              ./$file  --reporter junit --out ./tests/results/report_$file.xml && echo "Test $file Success!" || {cat ./tests/results/report_$file.xml; test_status=1; };
+            done;
+            if [ $test_status -ne 0 ]; then
+              echo "Tests failed. Exiting with error code."
+              exit 1
+            fi
             lcov --directory . -b ../pennylane_lightning/core/src --capture --output-file coverage.info  --ignore-errors mismatch # Catch2 causes mismatch errors that needs to be ignored
             lcov --remove coverage.info '/usr/*' --output-file coverage.info
             mv coverage.info coverage-${{ github.job }}-${{ matrix.pl_backend }}.info
@@ -235,10 +245,15 @@ jobs:
             cmake --build ./Build
             cd ./Build
             mkdir -p ./tests/results-${{ github.job }}-${{ matrix.pl_backend }}
+            test_status=0
             for file in *runner ; do 
               report_file="./tests/results-${{ github.job }}-${{ matrix.pl_backend }}/report_$file.xml";
-              ./$file --reporter junit --out $report_file && echo "Test $file Success!" || cat $report_file;
+              ./$file --reporter junit --out $report_file && echo "Test $file Success!" || { cat $report_file; test_status=1; }
             done;
+            if [ $test_status -ne 0 ]; then
+              echo "Tests failed. Exiting with error code."
+              exit 1
+            fi
             lcov --directory . -b ../pennylane_lightning/core/src --capture --output-file coverage.info  --ignore-errors mismatch # Catch2 causes mismatch errors that needs to be ignored
             lcov --remove coverage.info '/usr/*' --output-file coverage.info
             mv coverage.info coverage-${{ github.job }}-${{ matrix.pl_backend }}.info
@@ -337,7 +352,14 @@ jobs:
             cmake --build ./Build
             cd ./Build
             mkdir -p ./tests/results_multiple_backends
-            for file in *runner ; do ./$file  --reporter junit --out ./tests/results_multiple_backends/report_$file.xml && echo "Test $file Success!" || cat ./tests/results_multiple_backends/report_$file.xml; done;
+            test_status=0
+            for file in *runner ; do 
+              ./$file  --reporter junit --out ./tests/results_multiple_backends/report_$file.xml && echo "Test $file Success!" || { cat ./tests/results_multiple_backends/report_$file.xml; test_status=1; };
+            done;
+            if [ $test_status -ne 0 ]; then
+              echo "Tests failed. Exiting with error code."
+              exit 1
+            fi
 
       - name: Upload test results
         uses: actions/upload-artifact@v4
